config/routes.rb
# -*- encoding : utf-8 -*-
LoyalPassport::Engine.routes.draw do
  constraints lambda {|request| LoyalPassport.config.request_routes_constraints?(request) } do
    devise_for :users, :controllers => {
      :omniauth_callbacks      => "loyal_passport/users/omniauth_callbacks",
      :sessions                => "loyal_passport/users/sessions",
      :unlocks                 => "loyal_passport/users/unlocks",
      :registrations           => "loyal_passport/users/registrations",
      :passwords               => "loyal_passport/users/passwords",
      :confirmations           => "loyal_passport/users/confirmations"
    }

    devise_scope :user do
      namespace :users do
        namespace :profile do
          root :to => "informations#index"

          resources :oauth_logins, :only => [:new, :create, :index] do
            collection do
              post :cancel
            end
          end

          resources :informations, :only => [:index]
        end

      end

      get "users/auth/:provider/login(.:format)" => 'users/omniauth_callbacks#request_login',
        :as => :user_omniauth_request_login, :provider => ::LoyalPassport::OauthInfo.providers_regexp

      get "users/auth/:provider/login_callback(.:format)" => 'users/omniauth_callbacks#login_callback',
        :as => :user_omniauth_login_callback, :provider => ::LoyalPassport::OauthInfo.providers_regexp

      root :to => "users/sessions#new"
    end
  end

  # 管理后台
  constraints lambda {|request| LoyalAdmin.config.request_routes_constraints?(request) } do
    scope :admin, :module => :admin, :as => :admin do
      resources :users, :only => [:index, :show, :edit, :update]

      namespace :loyal_passport do
        resources :roles
        resources :assignments
      end
    end
  end

end

app/controllers/loyal_passport/users/profile/informations_controller.rb
# -*- encoding : utf-8 -*-
module LoyalPassport::Users::Profile
  class InformationsController < ::DeviseController
    include ::LoyalPassport::Controllers::UsersBasic

    before_filter do |controller|
      controller.send :authenticate_user!, :force => true
    end

    # users/profile/informations
    def index

    end
  end
end

app/controllers/loyal_passport/users/profile/oauth_logins_controller.rb
# -*- encoding : utf-8 -*-
module LoyalPassport::Users::Profile
  class OauthLoginsController < ::DeviseController
    include ::LoyalPassport::Controllers::UsersBasic

    before_filter do |controller|
      controller.send :authenticate_user!, :force => true
    end

    before_action :get_loyal_passport_omniauth_login_info, :only => [:new, :create]
    before_filter :_adjust_jump_when_loyal_passport_omniauth_login_info, :only => [:new, :create]

    def index
      @oauth_logins = current_user.oauth_logins.includes(:oauth_info)
    end

    def new
      @oauth_login = ::LoyalPassport::OauthLogin.new(
        :oauth_info_id => @loyal_passport_omniauth_login_info.id,
        :user_id => current_user.id
      )
    end

    def create
      @oauth_login = ::LoyalPassport::OauthLogin.new(oauth_login_params)

      if @oauth_login.save
        redirect_to (params[:return_to] || loyal_passport_app.users_profile_oauth_logins_url), :notice => "绑定帐号成功！"
      else
        render :new
      end
    end

    def cancel
      clear_loyal_passport_omniauth_info_session

      if params[:return_to].present?
        redirect_to params[:return_to]
      else
        redirect_to loyal_passport_app.users_profile_informations_url
      end
    end

    protected

    def _adjust_jump_when_loyal_passport_omniauth_login_info
      unless util_loyal_passport_omniauth_login_info_present?
        # 清理一下，其它的session
        clear_loyal_passport_omniauth_info_session

        if params[:return_to].present?
          redirect_to params[:return_to]
        else
          redirect_to loyal_passport_app.users_profile_informations_url
        end
      end
    end

    def oauth_login_params
      params[:oauth_login]
    end
  end
end

app/helpers/loyal_passport/users/profile/oauth_logins_helper.rb
# -*- encoding : utf-8 -*-
module LoyalPassport
  module Users::Profile::OauthLoginsHelper
  end
end

app/views/loyal_passport/users/profile/informations/index.html.erb
<h1>个人中心</h1>
<div class='informations show-fields'>
  <% if current_user.main_oauth_login_info %>
    <div class='field'>
      欢迎您来自
      <b><%= "#{current_user.main_oauth_login_info.provider_name}" %></b>
      的 <b><%= "#{current_user.main_oauth_login_info.nick_name}" %></b>
    </div>
  <% end %>

  <% if current_user.nick_name? %>
    <div class='field'>
      <label>昵称: </label>
      <%= current_user.nick_name %>
    </div>
  <% end %>

  <% if current_user.email? %>
    <div class='field'>
      <label>邮箱: </label>
      <%= current_user.email %>
    </div>
  <% end %>

  <div class='field'>
    <label>登录次数: </label>
    <%= current_user.sign_in_count %>
  </div>
  <div class='field'>
    <label>注册时间: </label>
    <%= l current_user.created_at %>
  </div>
  <div class='field'>
    <label>上一次登录时间: </label>
    <%= l current_user.last_sign_in_at %>
  </div>
</div>

<div class='other-links'>
  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <div class='link-line'>
      <%= link_to I18n.t('devise.views.edit_user_registration'), edit_registration_path(resource_name) %><br />
    </div>
  <% end -%>
</div>